volumes:
  db_data:

networks:
  app_network:
    driver: bridge

services:
  mongodb:
    image: mongo:6-jammy
    networks:
      - app_network
    volumes:
      - db_data:/data/db

  app:
    build: .
    networks:
      - app_network
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
