volumes:
  db_data:

networks:
  app_network:
    driver: bridge

services:
  mongodb:
    container_name: backend_test_task_mongodb
    image: mongo:6-jammy
    networks:
      - app_network
    volumes:
      - db_data:/data/db

  api:
    container_name: backend_test_task_api
    # TODO: configure API service
